### ISSUE TITLE
the nuget packages are broken for all versions

### ISSUE THREAD

**Issue by davecazz** [JetBrains/dotpeek-nupeek#5]
version 1.3 is trying to get Antlr2.Tools version 2.7.6.3 and can't find it when trying to restore packages

the other versions can't find Wave version 1.0

**Comment by derigel23** [comment]
All packages are on the gallery. There were issues with nuget.org today - may be it was affected.

**Comment by davecazz** [comment]
awesome, thanks for the quick response

**Comment by derigel23** [comment]
http://status.nuget.org/
